<?php

namespace Database\Seeders;

use App\Models\Client;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = [
            'INTERNI TIKET ZA AVPPI- JAVNI IZVRŠITELJI',
            'PRAVOBRANILAŠTVO GRADA NOVOG SADA- JAVNO PRAVOBRANILAŠTVO',
            'INTERNI TIKETI- ŠKOLA',
            'INTERNI TIKETI- SUD OPŠTE NADLEŽNOSTI',
            '67- BEOGRAD - 4 OS- stari sudovi',
            'ADA- OPŠTINA',
            'AGENCIJA ZA KVALIFIKACIJE- AGENCIJA',
            'AGRICOLE BANKA- BANKE / PREDUZEĆA',
            'ALEKSANDAR BOŠKOVIĆ- JAVNI IZVRŠITELJI CRNE GORE',
            'ALEKSANDAR DURKULIĆ - NS- JAVNI IZVRŠITELJI',
            'ALEKSANDAR NIKOLIĆ - BG- JAVNI IZVRŠITELJI',
            'ALEKSANDAR PAVLOVIĆ - KV- JAVNI IZVRŠITELJI',
            'ALEKSANDAR RISTOVIĆ - BG- JAVNI IZVRŠITELJI',
            'ALEKSANDAR TODOROVIĆ - SP- JAVNI IZVRŠITELJI',
            'ALEKSANDAR VULOVIĆ - BG- JAVNI IZVRŠITELJI',
            'ALEKSANDAR ZLOKOVIĆ- JAVNI IZVRŠITELJI CRNE GORE',
            'ALEKSANDRA ANTIĆ - LE- JAVNI IZVRŠITELJI',
            'ALEKSANDRA TOMKOVIĆ- JAVNI IZVRŠITELJI CRNE GORE',
            'ALEKSANDRA TREŠNJEV - BG- JAVNI IZVRŠITELJI',
            'ALIBUNAR- OPŠTINA',
            'ANA NIKIĆ- JAVNI IZVRŠITELJI CRNE GORE',
            'ANA PERENDIĆ - UE- JAVNI IZVRŠITELJI',
            'ANDRIJEVICA- OPŠTINA',
            'ARANĐELOVAC- OPŠTINA',
            'ARMIN CAMIĆ- JAVNI IZVRŠITELJI CRNE GORE',
            'AVP KOMISIJA- SUD OPŠTE NADLEŽNOSTI',
            'AVP KOMISIJA - KOMISIJA ZA STANDARDIZACIJU- OSNOVNI SUD',
            'AVP KOMISIJA - PRIVREDNI SUDOVI- PRIVREDNI SUDOVI',
            'AVP KOMISIJA- ODRZAVANJE- SUD OPŠTE NADLEŽNOSTI',
            'BABUŠNICA- OPŠTINA',
            'BAČ- OPŠTINA',
            'BAČKA PALANKA- OPŠTINA',
            'BAČKA TOPOLA- OPŠTINA',
            'BAČKI PETROVAC- OPŠTINA',
            'BALKAN- Javno preduzece',
            'BANCA INTESA- BANKE / PREDUZEĆA',
            'BANJA LUKA- OPŠTINA',
            'BANJA LUKA - MINISTARSTVO UPRAVE- OPŠTINA',
            'BANKA ON WHEELS- BANKE / PREDUZEĆA',
            'BAR- OPŠTINA',
            'BARAJEVO- OPŠTINA',
            'BELA CRKVA- OPŠTINA',
            'BELA PALANKA- OPŠTINA',
            'BEOGRAD- SKUPŠTINA GRADA BEOGRADA',
            'BEOGRAD-PUT- Javno preduzece',
            'BERANE- OPŠTINA',
            'BIJELJINA- OPŠTINA',
            'BIJELO POLJE- OPŠTINA',
            'BILEĆA- OPŠTINA',
            'BILJANA PETROVIĆ - BG- JAVNI IZVRŠITELJI',
            'BOGATIĆ- OPŠTINA',
            'BOJAN KOSTIĆ- BG- JAVNI IZVRŠITELJI',
            'BOJAN TOVARIŠIĆ - SU- JAVNI IZVRŠITELJI',
            'BOJANA MILANOVIĆ- JAVNI IZVRŠITELJI',
            'BOJNIK- OPŠTINA',
            'BOLJEVAC- OPŠTINA',
            'BOLNICA DR.BAKALOVIC VRŠAC- Javno preduzece',
            'BOR- OPŠTINA',
            'BORIS PAPIĆ-BG- JAVNI IZVRŠITELJI',
            'BORIS SREBOTNJAK - BG- JAVNI IZVRŠITELJI',
            'BRANISLAV AĆIMOV - BP- JAVNI IZVRŠITELJI',
            'BRANISLAV ČANTRIĆ - BG- JAVNI IZVRŠITELJI',
            'BRANISLAV RADOJČIĆ - BG- JAVNI IZVRŠITELJI',
            'BRANKA SAMARDŽIĆ- JAVNI IZVRŠITELJI CRNE GORE',
            'BRČKO DISTRIKT- OPŠTINA',
            'BUDVA- OPŠTINA',
            'CENTRI ZA KOMUNALNA PREDUZEĆA- Javno preduzece',
            'CETINJE- OPŠTINA',
            'CIVILNA ZASTITA- OPŠTINA',
            'CIVILNA ZASTITA- Javno preduzece',
            'CRNA TRAVA- OPŠTINA',
            'ČAČAK- PRIVREDNI SUDOVI',
            'ČETVRTI OPŠTINSKI SUD U BEOGRADU- stari sudovi',
            'SAŠA MIHAJLOVĆ - KV- JAVNI IZVRŠITELJI',
            'SAŠA ŠEKULJICA - SM- JAVNI IZVRŠITELJI',
            'SAVO ZAGORČIĆ - BG- JAVNI IZVRŠITELJI',
            'SDPR JUGOIMPORT- Javno preduzece',
            'SEKRETARIJAT ZA URBANIZAM BG- SKUPŠTINA GRADA BEOGRADA',
            'SENTA- OPŠTINA',
            'SETUP- OPŠTINA',
            'SEVESO- MINISTARSTVO',
            'SIEPA- Javno preduzece',
            'SIGMA CRVENKA- Javno preduzece',
            'SKLONIŠTA J.P.- Javno preduzece',
            'SKUPŠTINA - 27. MART- SKUPŠTINA GRADA BEOGRADA',
            'SKUPŠTINA - DRAGOSLAVA JOVANOVIĆA- SKUPŠTINA GRADA BEOGRADA',
            'SKUPŠTINA - GOLSVORDIJEVA- SKUPŠTINA GRADA BEOGRADA',
            'SKUPŠTINA - MASARIKOVA- SKUPŠTINA GRADA BEOGRADA',
            'SKUPŠTINA - MEKENZIJEVA- SKUPŠTINA GRADA BEOGRADA',
            'SKUPŠTINA - TIRŠOVA- SKUPŠTINA GRADA BEOGRADA',
            'SKUPŠTINA - TRG NIKOLE PAŠIĆA- SKUPŠTINA GRADA BEOGRADA',
            'SLUŽBENI GLASNIK- Javno preduzece',
            'Smederevo- OPŠTINA',
            'SMEDEREVO- OPŠTINA',
            'SOKO BANJA- OPŠTINA',
            'SOMBOR- OPŠTINA',
            'SOMBOR- PRIVREDNI SUDOVI',
            'SONJA LOZANIĆ - BG- JAVNI IZVRŠITELJI',
            'SPECIJALNA BOLNICA KOVIN- Javno preduzece',
            'SPECIJALNI SUD- SPECIJALNI SUD',
            'SPOMENICI KULTURE- SPOMENICI',
            'SPOMENICI KULTURE - BANJALUKA- SPOMENICI',
            'SPOMENICI KULTURE SREMSKA MITROVICA- SPOMENICI',
            'SRDJAN BUNJEVAC - MEGA- JAVNI IZVRŠITELJI',
            'SREMSKA MITROVICA- PRIVREDNI SUDOVI',
            'SREMSKA MITROVICA- OPŠTINA',
            'SŠ BRANISLAV NUŠIĆ-SOKO BANJA- ŠKOLA',
            'SŠ NIKOLA TESLA-BATOČINA- ŠKOLA',
            'SŠ sveti sava MIONICA- ŠKOLA',
            'SŠ ŽITORAĐA- ŠKOLA',
            'STANA ŽUNIĆ - KG- JAVNI IZVRŠITELJI',
            'STANKO FILIPOVIĆ - VR- JAVNI IZVRŠITELJI',
            'STEVAN PETROVIĆ - ZR- JAVNI IZVRŠITELJI',
            'SUBOTICA- OPŠTINA',
            'SUBOTICA- PRIVREDNI SUDOVI',
            'SUDOVI NEKRETNINE- OSTALO',
            'SURČIN- OPŠTINA',
            'SVETISLAV ČURĆIĆ - NS- JAVNI IZVRŠITELJI',
            'SVETLANA DEVRNJA - RU- JAVNI IZVRŠITELJI',
            'SVETLANA GARČEV PETERKA - ZR- JAVNI IZVRŠITELJI',
            'SVETLANA MANIĆ - BG- JAVNI IZVRŠITELJI',
            'SVETSKA BANKA - ANALIZA TOKA KRIVICE- OSTALO',
            'SVILAJNAC- OPŠTINA',
            'SVRLJIG- OPŠTINA',
            'ŠID- OPŠTINA',
            'TAMARA PAJKOVIĆ - BG- JAVNI IZVRŠITELJI',
            'TAMIŠ DUNAV DOO- Javno preduzece',
            'TEMERIN- OPŠTINA',
            'TEMPUS ET IUS- AGENCIJA ZA PRINUDNU NAPLATU',
            'TIVAT- OPŠTINA',
            'TOPOLA- OPŠTINA',
            'TREĆE OPŠTINSKO TUŽILAŠTVO U BEOGRADU- TUŽILAŠTVA I PRAVOBRANILAŠTVA',
            'TREĆI OPŠTINSKI SUD U BEOGRADU- stari sudovi',
            'TREĆI OSNOVNI SUD U BEOGRADU- SUD OPŠTE NADLEŽNOSTI',
            'TRGOVIŠTE- OPŠTINA',
            'TUTIN- OPŠTINA',
            'TUZILASTVO ZA ORGANIZOVANI KRIMINAL- TUŽILAŠTVA I PRAVOBRANILAŠTVA',
            'TUZILASTVO ZA RATNE ZLOCINE- TUŽILAŠTVA I PRAVOBRANILAŠTVA',
            'UBB- BANKE / PREDUZEĆA',
            'ULCINJ- OPŠTINA',
            'UNA SUČEVIĆ - RU- JAVNI IZVRŠITELJI',
            'UNICREDIT BANKA- BANKE / PREDUZEĆA',
            'UNION BANKA- BANKE / PREDUZEĆA',
            'UPRAVA CARINA- Javno preduzece',
            'UPRAVA CARINA- MINISTARSTVO',
            'UPRAVA ZA IZVRŠENJE KRIVIČNIH SANKCIJA- Javno preduzece',
            'URBANISTIČKI ZAVOD BEOGRADA- Javno preduzece',
            'UŽICE- OPŠTINA',
            'UŽICE- PRIVREDNI SUDOVI',
            'VALJEVO- PRIVREDNI SUDOVI',
            'VARVARIN- OPŠTINA',
            'VATROSPREM- Javno preduzece',
            'VELIKO GRADIŠTE- OPŠTINA',
            'VELJKO GUBERINIĆ - KU- JAVNI IZVRŠITELJI',
            'VELJKO RAIČEVIĆ - BG- JAVNI IZVRŠITELJI',
            'VESELIN ŠĆEPANOVIĆ- JAVNI IZVRŠITELJI CRNE GORE',
            'VESNA MARKOVIĆ - BG- JAVNI IZVRŠITELJI',
            'VIDAK LATKOVIĆ- JAVNI IZVRŠITELJI CRNE GORE',
            'VIDOJE STOJKOVIĆ - AR- JAVNI IZVRŠITELJI',
            'VISOKI SAVET SUDSTVA- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD SREMSKA MITROVICA- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U BEOGRADU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U ČAČKU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U JAGODINI- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U KOSOVSKOJ MITROVICI- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U KRAGUJEVCU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U KRALJEVU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U KRUŠEVCU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U LESKOVCU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U NEGOTINU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U NIŠU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U NOVOM PAZARU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U NOVOM SADU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U PANČEVU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U PIROTU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U POŽAREVCU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U PROKUPLJU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U SMEDEREVU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U SOMBORU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U SREMSKOJ MITROVICI- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U SUBOTICI- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U ŠAPCU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U UŽICU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U VALJEVU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U VRANJU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U VRANJU- OSTALO',
            'VIŠI SUD U ZAJEČARU- SUD OPŠTE NADLEŽNOSTI',
            'VIŠI SUD U ZRENJANINU- SUD OPŠTE NADLEŽNOSTI',
            'VLADAN MILOSAVLJEVIĆ - PO- JAVNI IZVRŠITELJI',
            'VLADIMIR NIKOLIĆ - BG- JAVNI IZVRŠITELJI',
            'VLADIMIR PECELJ - MEGA- JAVNI IZVRŠITELJI',
            'VLADIMIR TRIFUNOVIĆ-PA- JAVNI IZVRŠITELJI',
            'VLADIMIR VUJOTIĆ- JAVNI IZVRŠITELJI CRNE GORE',
            'VLADIMIRCI- OPŠTINA',
            'VLASOTINCE- OPŠTINA',
            'VODOVOD I KANALIZACIJA- Javno preduzece',
            'VOGOŠĆA- OPŠTINA',
            'VOŽDOVAC- OPŠTINA',
            'VRANJE- OPŠTINA',
            'VRBAS- OPŠTINA',
            'VRŠAC- OPŠTINA',
            'VSS - JOVAN RADONJIĆ- SUD OPŠTE NADLEŽNOSTI',
            'VSS - VESNA JANJIĆ- SUD OPŠTE NADLEŽNOSTI',
            'VTS- PRIVREDNI SUDOVI',
            'ZAJEČAR- PRIVREDNI SUDOVI',
            'ZAJEČAR- OPŠTINA',
            'ZEMUN- OPŠTINA',
            'ZIS- SKUPŠTINA GRADA BEOGRADA',
            'ZOI84- Javno preduzece',
            'ZORICA MILOŠEVIĆ - PO- JAVNI IZVRŠITELJI',
            'ZORICA SELEČANIN - KV- JAVNI IZVRŠITELJI',
            'ZRENJANIN- OSNOVNI SUD',
            'ZRENJANIN- VIŠI SUD',
            'ZRENJANIN- PRIVREDNI SUDOVI',
            'ZVEZDARA- OPŠTINA',
            'ŽABARI- OPŠTINA',
            'ŽAGUBICA- OPŠTINA',
            'ŽARKO DIMITRIJEVIĆ - NI- JAVNI IZVRŠITELJI',
            'ŽELJKO ČAVIĆ - BG- JAVNI IZVRŠITELJI',
            'ŽITIŠTE- OPŠTINA',
            'ŽITORAĐA- OPŠTINA',
            'ŽIVAN MILINOV - NS- JAVNI IZVRŠITELJI',
        ];

        foreach ($clients as $client) {
            Client::create([
                'name' => $client,
            ]);
        }
    }
}
